name: Laravel

on:
  push:
    branches:
      - master

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets for production
        run: npm run production

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} 
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ${{ secrets.DEPLOY_LOCATION }}
            git fetch
            git checkout -f
            git pull origin master
            composer update
            /opt/plesk/php/7.4/bin/php artisan migrate
            /opt/plesk/php/7.4/bin/php artisan cache:clear
            /opt/plesk/php/7.4/bin/php artisan route:cache
            /opt/plesk/php/7.4/bin/php artisan config:cache
